### ISSUE TITLE
Add local environment option

### ISSUE THREAD

**Issue by thephw** [buildkite/test_collector_elixir#9]
It'd be nice to be able to run the test collector locally as well to collect more data on flakey tests, but without setting "CI" specifically since that has some other effects for our codebase. 

What do we think about adding `BuildkiteTestCollector.CiEnv.Local` to also respond to another unique environment variable? 

```elixir
defmodule BuildkiteTestCollector.CiEnv.Local do
  ...
  def detected? do
    "BUILDKITE_TEST_ANALYTICS_LOCAL" |> System.get_env() |> is_binary()
  end
end
```

**Comment by jimsynz** [comment]
Hi @thephw - sorry I didn't get back to you earlier - for some reason Github didn't notify me about this.  It should be very simple to add another CI detecting module for this job.  Feel free to open a PR.

**Comment by thephw** [comment]
Hey @jimsynz got a PR in #12
